project:
  type: book

book:
  title: "Data Visualization Booklet"
  author: "Selin Aytan, Idil Tuzkaya and Ozan Evkaya"
  favicon: polar-bear-airpods-no-background.png
  description: An illustrative booklet using various size data sets.
  keyword: data science, data visualization, big data, ggplot2, data wrangling
  sidebar: 
    background: "#B7E892"
    logo: SoM-image.jpeg
    search: true
  repo-url: https://github.com/oevkaya/DataViz-Booklet
  repo-subdir: book
  repo-branch: master
  repo-actions: [edit, issue, source]
  sharing: [twitter, facebook, linkedin]
  image: SoM-image.jpeg
  comments:
    giscus:
      repo: oevkaya/DataViz-Booklet
  open-graph:
    image: https://github.com/kevinheavey/modern-polars/raw/master/book/resized-og-polar-bear-airpods-no-background.png
    description: A Quarto-based booklet exploring data viz on small and big data sets.

  chapters:
    - index.qmd

format:
  html:
    theme:
      light: sandstone
    code-fold: true
    css: custom.css
    toc: true
    backgroundcolor: "#F5F5F5"

# good themes: default, cosmo, flatly, lumen, minty, pulse, sandstone, solar, united
# favourites: minty, cosmo
