project:
  type: book

book:
  title: "Data Visualization Booklet"
  author: "Selin Aytan, Idil Tuzkaya and Ozan Evkaya"
  favicon: polar-bear-airpods-no-background.png
  description: An illustrative booklet using various size data sets.
  keyword: polars, pandas, python, dataframe, performance, data science, data engineering
  url: https://kevinheavey.github.io/modern-polars/
  sidebar: 
    background: "#F5F5F5"
    logo: polar-bear-airpods-no-background.png
    search: true
  repo-url: https://github.com/kevinheavey/modern-polars/
  repo-subdir: book
  repo-branch: master
  repo-actions: [edit, issue, source]
  sharing: [twitter, facebook, linkedin]
  image: polar-bear-airpods-no-background.png
  comments:
    giscus:
      repo: kevinheavey/modern-polars
  open-graph:
    image: https://github.com/kevinheavey/modern-polars/raw/master/book/resized-og-polar-bear-airpods-no-background.png
    description: A side-by-side comparison of the Polars and Pandas libraries.

  chapters:
    - index.qmd
    - indexing.qmd
    - method_chaining.qmd
    - performance.qmd
    - tidy.qmd
    - timeseries.qmd
    - scaling.qmd
    - summary.qmd

format:
  html:
    theme:
      light: cosmo
    code-fold: false
    css: custom.css
    backgroundcolor: "#F5F5F5"



# good themes: default, cosmo, flatly, lumen, minty, pulse, sandstone, solar, united
# favourites: minty, cosmo
